package com.iwa.iwaid.consultoriomedico.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.time.LocalDate;

/**
 * Represents a patient in the system.
 * Each patient has an id, name, date of birth, gender, RFC , address, city, phone number, and email.
 */
@Data
@Entity
@Table(name = "patiens")
public class Patient {

    /**
     * The unique ID of the patient. This is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The name of the patient. This field is required  and should not exceed 30 characters.
     */
    @NotNull
    private String name;

    /**
     * The date of birth of the patient. This field is required.
     * This should be in the format 'yyyy-MM-dd' to be compatible with MySQL DATE.
     */
    @NotNull
    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;

    /**
     * The gender of the patient. This field is required  and should not exceed 10 characters.
     */
    @NotNull
    private String gender;

    /**
     * The RFC of the patient. This field is required  and should not exceed 13 characters.
     */
    @NotNull
    private String rfc;

    /**
     * The address of the patient. This field is required  and should not exceed 80 characters.
     */
    @NotNull
    private String address;

    /**
     * The city of the patient. This field is required  and should not exceed 45 characters.
     */
    @NotNull
    private String city;

    /**
     * The phone number of the patient. This field is required.
     */
    @NotNull
    @Column(name = "phone_number")
    private Long phoneNumber;

    /**
     * The email of the patient. This field is required.
     */
    @NotNull
    private String email;
}
